### ISSUE TITLE
Error: Unsupported file type "undefined"

### ISSUE THREAD

**Issue by avianheit07** [bower/decompress-zip#45]

**Comment by sindresorhus** [comment]
Unless you provide more info there nothing we can do to help you.

**Comment by avianheit07** [comment]
I already got this fixed. Sorry if I did not elaborate on this issue. Error was caused by an incorrect file format or incorrect way of compressing a file. Thanks anyway for responding.

**Comment by VictorioBerra** [comment]
@avianheit07 

> or incorrect way of compressing a file

Can you elaborate on how you fixed this?
